python /mnt/ewwe/yts/at/atppo/ppo/main.py \
    --actor_lr=1e-5 \
    --actor_path=/mnt/ewwe/yts/at/atppo/saved_models/v6.1.2-60 \
    --apex_level=2 \
    --audio_length=10 \
    --batch_size=8 \
    --critic_lr=1e-5 \
    --critic_path=/mnt/ewwe/yts/at/atppo/saved_models/word \
    --grad_acc=4 \
    --model_save_path=/mnt/ewwe/yts/at/atppo/saved_models \
    --model_name=v6.5 \
    --reward_path=/mnt/ewwe/yts/at/atppo/saved_models/sent \
    --save_interval=1 \
    --tokenizer_path=/mnt/ewwe/yts/at/models/robertaForV3 \
    --train_epochs=10 \
    --transcripts=/mnt/ewwe/yts/at/spotify-960/transForPPO.pkl