#! /bin/bash

li=(v4.3.6-25 v4.3.6-50 v4.3.6-75 v4.3.6-100 v4.3.6-125 v4.3.6-150 v4.3.6-175 v4.3.6-200)
for ((i=0;i<=7;i++))
do
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mintrec --dont_show --output_file result.csv --epochs 10 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mintrec --dont_show --output_file result.csv --epochs 10 --batch_size 16 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mintrec --dont_show --output_file result.csv --epochs 50 --patience 10 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mintrec --dont_show --output_file result.csv --epochs 50 --patience 10 --batch_size 16 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mintrec --dont_show --seed 3407 --output_file result.csv --epochs 10 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mintrec --dont_show --seed 3407 --output_file result.csv --epochs 10 --batch_size 16 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mintrec --dont_show --seed 3407 --output_file result.csv --epochs 50 --patience 10 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mintrec --dont_show --seed 3407 --output_file result.csv --epochs 50 --patience 10 --batch_size 16 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosi --dont_show --output_file result.csv --epochs 5 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosi --dont_show --output_file result.csv --epochs 5 --batch_size 16 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosi --dont_show --output_file result.csv --epochs 50 --patience 10 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosi --dont_show --output_file result.csv --epochs 50 --patience 10 --batch_size 16 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosi --dont_show --seed 3407 --output_file result.csv --epochs 5 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosi --dont_show --seed 3407 --output_file result.csv --epochs 5 --batch_size 16 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosi --dont_show --seed 3407 --output_file result.csv --epochs 50 --patience 10 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosi --dont_show --seed 3407 --output_file result.csv --epochs 50 --patience 10 --batch_size 16 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosei --dont_show --output_file result.csv --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosei --dont_show --output_file result.csv --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosei --dont_show --output_file result.csv --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosei --dont_show --output_file result.csv --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosei --dont_show --output_file result.csv --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]} --seed 3407
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosei --dont_show --output_file result.csv --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]} --seed 3407
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosei --dont_show --output_file result.csv --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]} --seed 3407
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task mosei --dont_show --output_file result.csv --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]} --seed 3407
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]} --seed 3407
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]} --seed 3407
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]} --seed 3407
CUDA_VISIBLE_DEVICES=0 python /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]} --seed 3407
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --multi_audio --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --multi_audio --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --multi_audio --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --multi_audio --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]}
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --multi_audio --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]} --seed 3407
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --multi_audio --last_conv_layer group --epochs 5 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]} --seed 3407
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --multi_audio --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 4 --lr 2e-5 --model models/${li[$i]} --seed 3407
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 /mnt/shared/yts/yts/mtt/main.py --system /mnt/shared/yts/yts --task iemocap --dont_show --output_file result.csv --train_mode eleventurn --use_turn_ids --multi_audio --last_conv_layer group --epochs 50 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model models/${li[$i]} --seed 3407
done