#! /bin/bash

lsc=(no no no no no no no no group group group group group no)
li=(v3.2.7-25 v3.2.7-50 v3.2.7-75 v3.2.7-100 v3.2.9-75 v3.2.9-100 v3.3.6-75 v3.3.6-100 v3.3.5-25 v3.3.5-50 v3.3.4-25 v3.3.4-50 v3.3.4-75 v3.3.7-25)
for ((i=0;i<=13;i++))
do
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 24 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 24 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 24 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 24 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 24 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 24 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 24 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 24 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 32 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 32 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 32 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 32 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 32 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 24 --accumulate_num 2 --lr 1e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 24 --accumulate_num 1 --lr 1e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 24 --accumulate_num 2 --lr 1e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 24 --accumulate_num 1 --lr 1e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 24 --accumulate_num 2 --lr 1e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 24 --accumulate_num 1 --lr 1e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 24 --accumulate_num 2 --lr 1e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task mosei --dont_show --output_file mosei.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 24 --accumulate_num 1 --lr 1e-5 --model saved_models/${li[$i]} --seed 3407
done
for ((i=4;i<=13;i++))
do
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 4 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 4 --lr 2e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 4 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 1 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 2 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 4 --lr 2e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 1 --lr 1e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 2 --lr 1e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 4 --lr 1e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 1 --lr 1e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 2 --lr 1e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 4 --lr 1e-5 --model saved_models/${li[$i]}
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 1 --lr 1e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 2 --lr 1e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 5 --batch_size 12 --accumulate_num 4 --lr 1e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 1 --lr 1e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 2 --lr 1e-5 --model saved_models/${li[$i]} --seed 3407
python -m torch.distributed.launch --nproc_per_node=4 /root/workspace/mtt/main.py --system /root/data/yts --task iemocap --dont_show --train_mode eleventurn --multi_audio --output_file iemocap.csv --last_conv_layer ${lsc[$i]} --epochs 50 --batch_size 12 --accumulate_num 4 --lr 1e-5 --model saved_models/${li[$i]} --seed 3407
done